// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

public interface EmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learn.proto.fullstack.EmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
