// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learn.proto.fullstack.Empty)
    com.google.protobuf.MessageOrBuilder {
}
