// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

public interface GetAllEmpResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learn.proto.fullstack.GetAllEmpRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  java.util.List<learn.proto.fullstack.Employee> 
      getEmployeesList();
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  learn.proto.fullstack.Employee getEmployees(int index);
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  java.util.List<? extends learn.proto.fullstack.EmployeeOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  learn.proto.fullstack.EmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
