// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

/**
 * Protobuf type {@code learn.proto.fullstack.GetAllEmpRes}
 */
public  final class GetAllEmpRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:learn.proto.fullstack.GetAllEmpRes)
    GetAllEmpResOrBuilder {
  // Use GetAllEmpRes.newBuilder() to construct.
  private GetAllEmpRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllEmpRes() {
    employees_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetAllEmpRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              employees_ = new java.util.ArrayList<learn.proto.fullstack.Employee>();
              mutable_bitField0_ |= 0x00000001;
            }
            employees_.add(
                input.readMessage(learn.proto.fullstack.Employee.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        employees_ = java.util.Collections.unmodifiableList(employees_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return learn.proto.fullstack.Schema.internal_static_learn_proto_fullstack_GetAllEmpRes_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return learn.proto.fullstack.Schema.internal_static_learn_proto_fullstack_GetAllEmpRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            learn.proto.fullstack.GetAllEmpRes.class, learn.proto.fullstack.GetAllEmpRes.Builder.class);
  }

  public static final int EMPLOYEES_FIELD_NUMBER = 1;
  private java.util.List<learn.proto.fullstack.Employee> employees_;
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  public java.util.List<learn.proto.fullstack.Employee> getEmployeesList() {
    return employees_;
  }
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  public java.util.List<? extends learn.proto.fullstack.EmployeeOrBuilder> 
      getEmployeesOrBuilderList() {
    return employees_;
  }
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  public int getEmployeesCount() {
    return employees_.size();
  }
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  public learn.proto.fullstack.Employee getEmployees(int index) {
    return employees_.get(index);
  }
  /**
   * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
   */
  public learn.proto.fullstack.EmployeeOrBuilder getEmployeesOrBuilder(
      int index) {
    return employees_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employees_.size(); i++) {
      output.writeMessage(1, employees_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < employees_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, employees_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof learn.proto.fullstack.GetAllEmpRes)) {
      return super.equals(obj);
    }
    learn.proto.fullstack.GetAllEmpRes other = (learn.proto.fullstack.GetAllEmpRes) obj;

    boolean result = true;
    result = result && getEmployeesList()
        .equals(other.getEmployeesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmployeesCount() > 0) {
      hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learn.proto.fullstack.GetAllEmpRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(learn.proto.fullstack.GetAllEmpRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code learn.proto.fullstack.GetAllEmpRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:learn.proto.fullstack.GetAllEmpRes)
      learn.proto.fullstack.GetAllEmpResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learn.proto.fullstack.Schema.internal_static_learn_proto_fullstack_GetAllEmpRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learn.proto.fullstack.Schema.internal_static_learn_proto_fullstack_GetAllEmpRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learn.proto.fullstack.GetAllEmpRes.class, learn.proto.fullstack.GetAllEmpRes.Builder.class);
    }

    // Construct using learn.proto.fullstack.GetAllEmpRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        employeesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return learn.proto.fullstack.Schema.internal_static_learn_proto_fullstack_GetAllEmpRes_descriptor;
    }

    public learn.proto.fullstack.GetAllEmpRes getDefaultInstanceForType() {
      return learn.proto.fullstack.GetAllEmpRes.getDefaultInstance();
    }

    public learn.proto.fullstack.GetAllEmpRes build() {
      learn.proto.fullstack.GetAllEmpRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public learn.proto.fullstack.GetAllEmpRes buildPartial() {
      learn.proto.fullstack.GetAllEmpRes result = new learn.proto.fullstack.GetAllEmpRes(this);
      int from_bitField0_ = bitField0_;
      if (employeesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.employees_ = employees_;
      } else {
        result.employees_ = employeesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof learn.proto.fullstack.GetAllEmpRes) {
        return mergeFrom((learn.proto.fullstack.GetAllEmpRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(learn.proto.fullstack.GetAllEmpRes other) {
      if (other == learn.proto.fullstack.GetAllEmpRes.getDefaultInstance()) return this;
      if (employeesBuilder_ == null) {
        if (!other.employees_.isEmpty()) {
          if (employees_.isEmpty()) {
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmployeesIsMutable();
            employees_.addAll(other.employees_);
          }
          onChanged();
        }
      } else {
        if (!other.employees_.isEmpty()) {
          if (employeesBuilder_.isEmpty()) {
            employeesBuilder_.dispose();
            employeesBuilder_ = null;
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
            employeesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeesFieldBuilder() : null;
          } else {
            employeesBuilder_.addAllMessages(other.employees_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      learn.proto.fullstack.GetAllEmpRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (learn.proto.fullstack.GetAllEmpRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<learn.proto.fullstack.Employee> employees_ =
      java.util.Collections.emptyList();
    private void ensureEmployeesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        employees_ = new java.util.ArrayList<learn.proto.fullstack.Employee>(employees_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        learn.proto.fullstack.Employee, learn.proto.fullstack.Employee.Builder, learn.proto.fullstack.EmployeeOrBuilder> employeesBuilder_;

    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public java.util.List<learn.proto.fullstack.Employee> getEmployeesList() {
      if (employeesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employees_);
      } else {
        return employeesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public int getEmployeesCount() {
      if (employeesBuilder_ == null) {
        return employees_.size();
      } else {
        return employeesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public learn.proto.fullstack.Employee getEmployees(int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);
      } else {
        return employeesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder setEmployees(
        int index, learn.proto.fullstack.Employee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.set(index, value);
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder setEmployees(
        int index, learn.proto.fullstack.Employee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder addEmployees(learn.proto.fullstack.Employee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder addEmployees(
        int index, learn.proto.fullstack.Employee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(index, value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder addEmployees(
        learn.proto.fullstack.Employee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder addEmployees(
        int index, learn.proto.fullstack.Employee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder addAllEmployees(
        java.lang.Iterable<? extends learn.proto.fullstack.Employee> values) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employees_);
        onChanged();
      } else {
        employeesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder clearEmployees() {
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        employeesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public Builder removeEmployees(int index) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.remove(index);
        onChanged();
      } else {
        employeesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public learn.proto.fullstack.Employee.Builder getEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public learn.proto.fullstack.EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);  } else {
        return employeesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public java.util.List<? extends learn.proto.fullstack.EmployeeOrBuilder> 
         getEmployeesOrBuilderList() {
      if (employeesBuilder_ != null) {
        return employeesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employees_);
      }
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public learn.proto.fullstack.Employee.Builder addEmployeesBuilder() {
      return getEmployeesFieldBuilder().addBuilder(
          learn.proto.fullstack.Employee.getDefaultInstance());
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public learn.proto.fullstack.Employee.Builder addEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().addBuilder(
          index, learn.proto.fullstack.Employee.getDefaultInstance());
    }
    /**
     * <code>repeated .learn.proto.fullstack.Employee employees = 1;</code>
     */
    public java.util.List<learn.proto.fullstack.Employee.Builder> 
         getEmployeesBuilderList() {
      return getEmployeesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        learn.proto.fullstack.Employee, learn.proto.fullstack.Employee.Builder, learn.proto.fullstack.EmployeeOrBuilder> 
        getEmployeesFieldBuilder() {
      if (employeesBuilder_ == null) {
        employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            learn.proto.fullstack.Employee, learn.proto.fullstack.Employee.Builder, learn.proto.fullstack.EmployeeOrBuilder>(
                employees_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        employees_ = null;
      }
      return employeesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:learn.proto.fullstack.GetAllEmpRes)
  }

  // @@protoc_insertion_point(class_scope:learn.proto.fullstack.GetAllEmpRes)
  private static final learn.proto.fullstack.GetAllEmpRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new learn.proto.fullstack.GetAllEmpRes();
  }

  public static learn.proto.fullstack.GetAllEmpRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllEmpRes>
      PARSER = new com.google.protobuf.AbstractParser<GetAllEmpRes>() {
    public GetAllEmpRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetAllEmpRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllEmpRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllEmpRes> getParserForType() {
    return PARSER;
  }

  public learn.proto.fullstack.GetAllEmpRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

