// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_GetAllEmpRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_GetAllEmpRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_CreateEmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_CreateEmployeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_EmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_EmployeeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_UpdateEmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_UpdateEmployeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_UpdateEmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_UpdateEmployeeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learn_proto_fullstack_EmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_learn_proto_fullstack_EmployeeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\025learn.proto.fullstack\"O\n" +
      "\010Employee\022\n\n\002id\030\001 \001(\003\022\022\n\nfirst_name\030\002 \001(" +
      "\t\022\021\n\tlast_name\030\003 \001(\t\022\020\n\010email_id\030\004 \001(\t\"\007" +
      "\n\005Empty\"B\n\014GetAllEmpRes\0222\n\temployees\030\001 \003" +
      "(\0132\037.learn.proto.fullstack.Employee\"J\n\025C" +
      "reateEmployeeRequest\0221\n\010employee\030\001 \001(\0132\037" +
      ".learn.proto.fullstack.Employee\"\"\n\020Emplo" +
      "yeeResponse\022\016\n\006status\030\001 \001(\t\"\\\n\025UpdateEmp" +
      "loyeeRequest\022\n\n\002id\030\001 \001(\003\022\022\n\nfirst_name\030\002" +
      " \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\020\n\010email_id\030\004 \001(",
      "\t\"K\n\026UpdateEmployeeResponse\0221\n\010employee\030" +
      "\001 \001(\0132\037.learn.proto.fullstack.Employee\"\035" +
      "\n\017EmployeeRequest\022\n\n\002id\030\001 \001(\0032\204\004\n\017Employ" +
      "eeService\022V\n\017GetAllEmployees\022\034.learn.pro" +
      "to.fullstack.Empty\032#.learn.proto.fullsta" +
      "ck.GetAllEmpRes\"\000\022i\n\016CreateEmployee\022,.le" +
      "arn.proto.fullstack.CreateEmployeeReques" +
      "t\032\'.learn.proto.fullstack.EmployeeRespon" +
      "se\"\000\022o\n\016UpdateEmployee\022,.learn.proto.ful" +
      "lstack.UpdateEmployeeRequest\032-.learn.pro",
      "to.fullstack.UpdateEmployeeResponse\"\000\022c\n" +
      "\016DeleteEmployee\022&.learn.proto.fullstack." +
      "EmployeeRequest\032\'.learn.proto.fullstack." +
      "EmployeeResponse\"\000\022X\n\013getEmployee\022&.lear" +
      "n.proto.fullstack.EmployeeRequest\032\037.lear" +
      "n.proto.fullstack.Employee\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_learn_proto_fullstack_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_learn_proto_fullstack_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_Employee_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "EmailId", });
    internal_static_learn_proto_fullstack_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_learn_proto_fullstack_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_learn_proto_fullstack_GetAllEmpRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_learn_proto_fullstack_GetAllEmpRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_GetAllEmpRes_descriptor,
        new java.lang.String[] { "Employees", });
    internal_static_learn_proto_fullstack_CreateEmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_learn_proto_fullstack_CreateEmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_CreateEmployeeRequest_descriptor,
        new java.lang.String[] { "Employee", });
    internal_static_learn_proto_fullstack_EmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_learn_proto_fullstack_EmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_EmployeeResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_learn_proto_fullstack_UpdateEmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_learn_proto_fullstack_UpdateEmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_UpdateEmployeeRequest_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "EmailId", });
    internal_static_learn_proto_fullstack_UpdateEmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_learn_proto_fullstack_UpdateEmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_UpdateEmployeeResponse_descriptor,
        new java.lang.String[] { "Employee", });
    internal_static_learn_proto_fullstack_EmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_learn_proto_fullstack_EmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_learn_proto_fullstack_EmployeeRequest_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
