// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

public interface UpdateEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learn.proto.fullstack.UpdateEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string first_name = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email_id = 4;</code>
   */
  java.lang.String getEmailId();
  /**
   * <code>string email_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();
}
