// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package learn.proto.fullstack;

public interface UpdateEmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learn.proto.fullstack.UpdateEmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.learn.proto.fullstack.Employee employee = 1;</code>
   */
  boolean hasEmployee();
  /**
   * <code>.learn.proto.fullstack.Employee employee = 1;</code>
   */
  learn.proto.fullstack.Employee getEmployee();
  /**
   * <code>.learn.proto.fullstack.Employee employee = 1;</code>
   */
  learn.proto.fullstack.EmployeeOrBuilder getEmployeeOrBuilder();
}
